project:
  type: website
  output-dir: docs

website:
  title: "Mateo's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - relevant_coursework.qmd
      - resume.qmd
      - Project.qmd
  page-footer:
    left: Copyright 2026, Mateo Mori
    right: Hola!

format:
  html:
    theme: flatly
    mainfont: Teachers
    css: styles.css
    toc: true
    page-layout: full
    lightbox: true

editor: visual

