project:
  type: website
  output-dir: docs

website:
  title: "Mateo's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
  page-footer:
    background: light
    left: Copyright 2026, Mateo Mori
    right: Hola!

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

